### ISSUE TITLE
Version 7.9.1 対応は可能でしょうか？

### ISSUE THREAD

**Issue by asanobm** [sugikeitter/elasticsearch-kibana-docker#5]
Hello @sugikeitter. this repository is very good information.

I want to update elasticsearch, kibana version( 7.9.1).

Thank you.

**Comment by sugikeitter** [comment]
@kimbm-dev Thank you for creating a issue! I updated code and closed this issue.
issue作っていただきありがとうございます！マイナーバージョン変更でDockerfileのバージョン変更だけで動いたので対応いたしました！
